### ISSUE TITLE
SMSG_BATTLE_PAY_GET_PRODUCT_LIST_RESPONSE - structure for 5.4.8 18414

### ISSUE THREAD

**Issue by akrom23** [ChipLeo/WowPacketParser#24]
Hi Chipleo,
i've got question about this packet: SMSG_BATTLE_PAY_GET_PRODUCT_LIST_RESPONSE.
Here's my structure of this packet: https://pastebin.com/51aaAcB0. I think this is the proper structure, but i've encountred some problems with it while parsing this packet from WowFreakz server (they implemented the BattlePay Shop some time ago) - you can see it here: https://pastebin.com/Q8GbzDjM.
Could you check this structure with your sniffs/files? Or give some tip, where the problem is. The sub is: sub_74F354
Best regards.

**Comment by ChipLeo** [comment]
It's work fine: https://pastebin.com/HAVLNDKd

**Comment by akrom23** [comment]
So could you sniff and parse WoWfreakz? Maybe their devs do something with wow.exe

**Comment by ChipLeo** [comment]
Thier devs created wrong handler for SMSG_BATTLE_PAY_GET_PRODUCT_LIST_RESPONSE (not wow.exe).

**Comment by akrom23** [comment]
Ok, so everything is clear. Thx a lot.

**Comment by ChipLeo** [comment]
Where you get names of variables?

**Comment by akrom23** [comment]
Comparison with WoD structures and then determining the right order.
One more question - do you have any sniffs about char boosting? :)

**Comment by ChipLeo** [comment]
I dont have this.

**Comment by akrom23** [comment]
Ok.

**Comment by akrom23** [comment]
Another request - do you have any sniffs about raid browser (a.k.a. LFR) from 5.4.8?

**Comment by ChipLeo** [comment]
I dont have this.

**Comment by akrom23** [comment]
Thx anyway :)
